package analysis;

import ast.*;
import java.util.*;

public class StaticAnalyzer {

    private ProgramNode program;
    private Map<String, Integer> variables;
    private Set<String> facts;

    public StaticAnalyzer(
            ProgramNode program,
            Map<String, Integer> variables,
            Set<String> facts) {
        this.program = program;
        this.variables = variables;
        this.facts = facts;
    }

    public void analyze() {
        detectConflicts();
        detectRedundantRules();
        detectPotentiallyInactiveRules();
    }

    // =========================================
    // CONFLICTS
    // =========================================
    private void detectConflicts() {
        Map<String, List<RuleNode>> actionMap = new HashMap<>();

        for (RuleNode rule : program.getRules()) {
            String action = rule.getAction().getIdentifier();
            actionMap.putIfAbsent(action, new ArrayList<>());
            actionMap.get(action).add(rule);
        }

        for (String action : actionMap.keySet()) {
            List<RuleNode> rules = actionMap.get(action);

            if (rules.size() > 1) {
                // Un conflicto real requiere que las condiciones sean distintas.
                // Si todas tienen la misma condición, es Redundancia, no Conflicto.
                boolean realConflict = false;
                String firstCond = conditionToString(rules.get(0).getCondition());
                List<String> ruleNames = new ArrayList<>();

                for (RuleNode r : rules) {
                    ruleNames.add(r.getName());
                    if (!conditionToString(r.getCondition()).equals(firstCond)) {
                        realConflict = true;
                    }
                }

                if (realConflict) {
                    System.out.println(
                            "Action " + action +
                                    " generated by " +
                                    String.join(", ", ruleNames)
                    );
                }
            }
        }
    }

    // =========================================
    // REDUNDANT RULES
    // =========================================
    private void detectRedundantRules() {
        List<RuleNode> rules = program.getRules();

        for (int i = 0; i < rules.size(); i++) {
            for (int j = i + 1; j < rules.size(); j++) {
                RuleNode r1 = rules.get(i);
                RuleNode r2 = rules.get(j);

                boolean sameAction = r1.getAction().getIdentifier()
                        .equals(r2.getAction().getIdentifier());

                boolean sameCondition = conditionToString(r1.getCondition())
                        .equals(conditionToString(r2.getCondition()));

                if (sameAction && sameCondition) {
                    System.out.println(
                            "Redundant rules: " +
                                    r1.getName() +
                                    ", " +
                                    r2.getName()
                    );
                }
            }
        }
    }

    // =========================================
    // POTENTIALLY INACTIVE RULES
    // =========================================
    // =========================================
    // POTENTIALLY INACTIVE RULES
    // =========================================
    private void detectPotentiallyInactiveRules() {
        List<RuleNode> allRules = program.getRules();

        // Si solo hay una regla en todo el programa, no se considera "aislada" o inactiva (Caso 3)
        if (allRules.size() <= 1) {
            return;
        }

        for (RuleNode rule : allRules) {
            if (rule.getCondition() instanceof ComparisonNode cmp) {

                int value = variables.getOrDefault(cmp.getIdentifier(), 0);
                int target = cmp.getValue();

                boolean result = switch (cmp.getOperator()) {
                    case ">" -> value > target;
                    case "<" -> value < target;
                    case "=" -> value == target;
                    default -> false;
                };

                // Si NO se cumple la condición en el estado inicial
                if (!result) {
                    String producedFact = rule.getAction().getIdentifier();
                    boolean usedSomewhere = false;

                    // 1. Revisar si otras reglas usan ese fact en su CONDICIÓN
                    for (RuleNode other : allRules) {
                        if (conditionUsesFact(other.getCondition(), producedFact)) {
                            usedSomewhere = true;
                            break;
                        }
                    }

                    // 2. Validar si la regla es redundante con otra (Caso 7)
                    boolean hasRedundancy = false;
                    for (RuleNode other : allRules) {
                        if (other != rule) {
                            boolean sameAction = other.getAction().getIdentifier().equals(producedFact);
                            boolean sameCondition = conditionToString(other.getCondition())
                                    .equals(conditionToString(rule.getCondition()));
                            if (sameAction && sameCondition) {
                                hasRedundancy = true;
                                break;
                            }
                        }
                    }

                    // 3. Para el Caso 8: La regla está inactiva si está completamente aislada.
                    // Revisamos si la variable que usa en su condición (ej. "humidity") es usada por alguna otra regla.
                    // Si nadie más comparte esa variable ni ese hecho, la regla está totalmente aislada del flujo.
                    boolean sharesContext = false;
                    for (RuleNode other : allRules) {
                        if (other != rule) {
                            if (conditionToString(other.getCondition()).contains(cmp.getIdentifier()) ||
                                    other.getAction().getIdentifier().equals(cmp.getIdentifier())) {
                                sharesContext = true;
                                break;
                            }
                        }
                    }

                    // Se marca como inactiva si:
                    // - Su condición es falsa.
                    // - Su consecuencia no se usa en el if de nadie (no genera encadenamiento).
                    // - No es una redundancia.
                    // - Está aislada (no comparte variables de condición con el flujo de las otras reglas).
                    if (!usedSomewhere && !hasRedundancy && !sharesContext) {
                        System.out.println(
                                "Potentially inactive rule: " + rule.getName()
                        );
                    }
                }
            }
        }
    }

    private boolean conditionUsesFact(ConditionNode condition, String fact) {
        if (condition instanceof FactNode factNode) {
            return factNode.getIdentifier().equals(fact);
        }

        if (condition instanceof AndNode andNode) {
            return conditionUsesFact(andNode.getLeft(), fact)
                    || conditionUsesFact(andNode.getRight(), fact);
        }

        return false;
    }

    // =========================================
    // UTILIDAD
    // =========================================
    private String conditionToString(ConditionNode condition) {
        if (condition instanceof ComparisonNode cmp) {
            return cmp.getIdentifier()
                    + cmp.getOperator()
                    + cmp.getValue();
        }

        if (condition instanceof FactNode fact) {
            return fact.getIdentifier();
        }

        if (condition instanceof AndNode andNode) {
            return conditionToString(andNode.getLeft())
                    + "AND" +
                    conditionToString(andNode.getRight());
        }

        return "";
    }
}