package analysis;

import ast.*;

import java.util.*;

public class StaticAnalyzer {

    private ProgramNode program;

    private Map<String, Integer> variables;

    private Set<String> facts;

    public StaticAnalyzer(
            ProgramNode program,
            Map<String, Integer> variables,
            Set<String> facts) {

        this.program = program;
        this.variables = variables;
        this.facts = facts;
    }

    public void analyze() {

        detectConflicts();

        detectRedundantRules();

        detectPotentiallyInactiveRules();
    }

    // =========================================
    // CONFLICTS
    // =========================================

    private void detectConflicts() {

        Map<String, List<String>> actionMap =
                new HashMap<>();

        for (RuleNode rule : program.getRules()) {

            String action =
                    rule.getAction().getIdentifier();

            actionMap.putIfAbsent(
                    action,
                    new ArrayList<>()
            );

            actionMap.get(action)
                    .add(rule.getName());
        }

        for (String action : actionMap.keySet()) {

            List<String> rules =
                    actionMap.get(action);

            if (rules.size() > 1) {

                System.out.println(
                        "Action " + action +
                                " generated by " +
                                String.join(", ", rules)
                );
            }
        }
    }

    // =========================================
    // REDUNDANT RULES
    // =========================================

    private void detectRedundantRules() {

        List<RuleNode> rules =
                program.getRules();

        for (int i = 0; i < rules.size(); i++) {

            for (int j = i + 1;
                 j < rules.size();
                 j++) {

                RuleNode r1 = rules.get(i);

                RuleNode r2 = rules.get(j);

                boolean sameAction =
                        r1.getAction()
                                .getIdentifier()
                                .equals(
                                        r2.getAction()
                                                .getIdentifier()
                                );

                boolean sameCondition =
                        conditionToString(
                                r1.getCondition()
                        ).equals(
                                conditionToString(
                                        r2.getCondition()
                                )
                        );

                if (sameAction && sameCondition) {

                    System.out.println(
                            "Redundant rules: " +
                                    r1.getName() +
                                    ", " +
                                    r2.getName()
                    );
                }
            }
        }
    }

    // =========================================
    // POTENTIALLY INACTIVE RULES
    // =========================================

    private void detectPotentiallyInactiveRules() {

        for (RuleNode rule : program.getRules()) {

            // solo analizar comparaciones simples
            if (rule.getCondition() instanceof ComparisonNode cmp) {

                int value =
                        variables.getOrDefault(
                                cmp.getIdentifier(),
                                0
                        );

                int target = cmp.getValue();

                boolean result = switch (cmp.getOperator()) {

                    case ">" -> value > target;

                    case "<" -> value < target;

                    case "=" -> value == target;

                    default -> false;
                };

                if (!result) {

                    System.out.println(
                            "Potentially inactive rule: "
                                    + rule.getName()
                    );
                }
            }
        }
    }

    private boolean evaluateCondition(
            ConditionNode condition) {

        // AND
        if (condition instanceof AndNode andNode) {

            return evaluateCondition(
                    andNode.getLeft())
                    &&
                    evaluateCondition(
                            andNode.getRight());
        }

        // COMPARISON
        if (condition instanceof ComparisonNode cmp) {

            int value =
                    variables.getOrDefault(
                            cmp.getIdentifier(),
                            0
                    );

            int target = cmp.getValue();

            return switch (cmp.getOperator()) {

                case ">" -> value > target;

                case "<" -> value < target;

                case "=" -> value == target;

                default -> false;
            };
        }

        // FACT
        if (condition instanceof FactNode fact) {

            return facts.contains(
                    fact.getIdentifier()
            );
        }

        return false;
    }

    // =========================================
    // UTILIDAD
    // =========================================

    private String conditionToString(
            ConditionNode condition) {

        if (condition instanceof ComparisonNode cmp) {

            return cmp.getIdentifier()
                    + cmp.getOperator()
                    + cmp.getValue();
        }

        if (condition instanceof FactNode fact) {

            return fact.getIdentifier();
        }

        if (condition instanceof AndNode andNode) {

            return conditionToString(
                    andNode.getLeft())
                    + "AND" +
                    conditionToString(
                            andNode.getRight());
        }

        return "";
    }

}